/*
** EPITECH PROJECT, 2026
** ASM_to_bytecode
** File description:
** keywords_table
*/

#include "writes.h"

const keywords_t keywords[NB_KEYWORDS] = {
    /* Data movement */
    [MOV] = {"mov", MOV, write_mov},
    [MOVZX] = {"movzx", MOVZX, write_movzx},
    [MOVSX] = {"movsx", MOVSX, write_movsx},
    [LEA] = {"lea", LEA, write_lea},
    [PUSH] = {"push", PUSH, write_push},
    [POP] = {"pop", POP, write_pop},
    [XCHG] = {"xchg", XCHG, write_xchg},
    [CMOV] = {"cmov", CMOV, write_cmov},
    /* Arithmetic */
    [ADD] = {"add", ADD, write_add},
    [SUB] = {"sub", SUB, write_sub},
    [INC] = {"inc", INC, write_inc},
    [DEC] = {"dec", DEC, write_dec},
    [NEG] = {"neg", NEG, write_neg},
    [IMUL] = {"imul", IMUL, write_imul},
    [MUL] = {"mul", MUL, write_mul},
    [IDIV] = {"idiv", IDIV, write_idiv},
    [DIV] = {"div", DIV, write_div},
    /* Bitwise and shift */
    [AND] = {"and", AND, write_and},
    [OR] = {"or", OR, write_or},
    [XOR] = {"xor", XOR, write_xor},
    [NOT] = {"not", NOT, write_not},
    [SHL] = {"shl", SHL, write_shl},
    [SHR] = {"shr", SHR, write_shr},
    [SAR] = {"sar", SAR, write_sar},
    [ROL] = {"rol", ROL, write_rol},
    [ROR] = {"ror", ROR, write_ror},
    [BSWAP] = {"bswap", BSWAP, write_bswap},
    /* Comparison and flags */
    [CMP] = {"cmp", CMP, write_cmp},
    [TEST] = {"test", TEST, write_test},
    [SETE] = {"sete", SETE, write_sete},
    [SETNE] = {"setne", SETNE, write_setne},
    [SETL] = {"setl", SETL, write_setl},
    [SETG] = {"setg", SETG, write_setg},
    [SETLE] = {"setle", SETLE, write_setle},
    [SETGE] = {"setge", SETGE, write_setge},
    /* Jumps */
    [JMP] = {"jmp", JMP, write_jmp},
    [JE] = {"je", JE, write_je},
    [JZ] = {"jz", JZ, write_jz},
    [JNE] = {"jne", JNE, write_jne},
    [JNZ] = {"jnz", JNZ, write_jnz},
    [JL] = {"jl", JL, write_jl},
    [JNGE] = {"jnge", JNGE, write_jnge},
    [JG] = {"jg", JG, write_jg},
    [JNLE] = {"jnle", JNLE, write_jnle},
    [JLE] = {"jle", JLE, write_jle},
    [JNG] = {"jng", JNG, write_jng},
    [JGE] = {"jge", JGE, write_jge},
    [JNL] = {"jnl", JNL, write_jnl},
    [JB] = {"jb", JB, write_jb},
    [JNAE] = {"jnae", JNAE, write_jnae},
    [JA] = {"ja", JA, write_ja},
    [JNBE] = {"jnbe", JNBE, write_jnbe},
    [JS] = {"js", JS, write_js},
    [JNS] = {"jns", JNS, write_jns},
    [JO] = {"jo", JO, write_jo},
    [JNO] = {"jno", JNO, write_jno},
    /* Function calls and returns */
    [CALL] = {"call", CALL, write_call},
    [RET] = {"ret", RET, write_ret},
    [LEAVE] = {"leave", LEAVE, write_leave},
    [ENTER] = {"enter", ENTER, write_enter},
    /* Memory and string operations */
    [MOVS] = {"movs", MOVS, write_movs},
    [STOS] = {"stos", STOS, write_stos},
    [LODS] = {"lods", LODS, write_lods},
    [SCAS] = {"scas", SCAS, write_scas},
    [CMPS] = {"cmps", CMPS, write_cmps},
    [REP] = {"rep", REP, write_rep},
    [REPE] = {"repe", REPE, write_repe},
    [REPZ] = {"repz", REPZ, write_repz},
    [REPNE] = {"repne", REPNE, write_repne},
    [REPNZ] = {"repnz", REPNZ, write_repnz},
    /* System and control */
    [SYSCALL] = {"syscall", SYSCALL, write_syscall},
    [INT] = {"int", INT, write_int},
    [NOP] = {"nop", NOP, write_nop},
    [HLT] = {"hlt", HLT, write_hlt},
    [CPUID] = {"cpuid", CPUID, write_cpuid},
    [RDTSC] = {"rdtsc", RDTSC, write_rdtsc},
    /* NASM assembler directives */
    [SECTION_TEXT] = {"section .text", SECTION_TEXT, write_section_text},
    [SECTION_DATA] = {"section .data", SECTION_DATA, write_section_data},
    [SECTION_BSS] = {"section .bss", SECTION_BSS, write_section_bss},
    [GLOBAL] = {"global", GLOBAL, write_global},
    [EXTERN] = {"extern", EXTERN, write_extern},
    [DB] = {"db", DB, write_db},
    [DW] = {"dw", DW, write_dw},
    [DD] = {"dd", DD, write_dd},
    [DQ] = {"dq", DQ, write_dq},
    [RESB] = {"resb", RESB, write_resb},
    [EQU] = {"equ", EQU, write_equ},
    [DEFINE] = {"%define", DEFINE, write_define},
    [TIMES] = {"times", TIMES, write_times},
};
